spring:
  # debug: false
  batch:
    job:
      enabled: true
    initialize-schema: always

  datasource:
    url: jdbc:postgresql://localhost:5432/Bib
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mmaannddrr0066

